# POSTTEST 7 KECERDASAN BUATAN

<ul>
    <li> Nama : Denissa Putri Maha Rani
    <li> NIM  : 2009106079
</ul>

### Tensor flow

TensorFlow merupakan library open-source yang digunakan untuk Machine Learning dan Tensor diklasifikasikan menjadi 2 => Constant Tensor dan Variable Tensor

#### Constant Tensor 

<ul>
    <li> tf.constant()
    <li> tf.zeros()
    <li> tf.fill()
    <li> tf.random()
    <li> tf.using_to_tensor()
<ul>

#### Variabel Tensor

<li> tf.variable()

#### Dimension Display

<li> tf.shape(), tf.get_shape()
<li> tf.reshape()
<li> tf.expand_dims()
<li> tf.squeeze()
<li> tf.transpose()
<li> tf.broadcast_to()

#### Arithmetic Operators

<li> tf.add()     : penjumlahan
<li> tf.subtract() : pengurangan
<li> tf.multiply() : perkalian
<li> tf.divide()   : pembagian
<li> tf.math.log() :logaritma
<li> tf.pow : pangkat

#### Tensor statistic collection

<li> tf.argmax() : untuk mengalkulasi posisi nilai maksimum
<li> tf.argmin() : untuk mengalkulasi posisi nilai minimum

#### Tensor concatenation

<li> untuk menggabungkan vektor berdasarkan dimensi yang telah ditentukan dengan tetap menjaga agar dimensi lain tidak berubah <br>
<li> tf.concat()

In [123]:
#import library 
import tensorflow as tf

#### Membuat tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [62]:
#membuat tensor dengan nilai acak/random 
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1 )
random_tensor.numpy()

array([[-0.8559895 ,  0.93666625,  0.55710965,  0.07463042, -1.6017824 ],
       [ 0.8832085 , -1.6398144 ,  2.1169775 ,  0.48650688,  0.8811853 ],
       [ 1.1792054 ,  0.31829008, -0.30523288, -0.5744346 ,  1.6413461 ],
       [ 0.18569663, -1.4471521 ,  0.32309735, -0.1825322 , -1.2932976 ],
       [-1.113902  , -1.0944788 ,  0.01676212,  0.42491904,  0.93900865]],
      dtype=float32)

#### Membuat tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [63]:
#membuat list bil.prima
bil_prima = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53, 59, 61, 67, 71],[73, 79, 83, 89, 97]]

#membuat tensor dari list bil.prima
prime_tensor = tf.convert_to_tensor(bil_prima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

#### Tampilkan dimensi dari kedua variable tersebut

In [65]:
#dimensi random_tensor
random_tensor.get_shape()

#dimensi prime_tensor
prime_tensor.get_shape()

print(f'Dimensi random_tensor : {random_tensor.get_shape()}',
      f'Dimensi prime_tensor  : {prime_tensor.get_shape()}',
      sep='\n')

Dimensi random_tensor : (5, 5)
Dimensi prime_tensor  : (5, 5)


#### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [113]:
#penjumlahan
print(f'Hasil penjumlahan :')
tf.add(random_tensor, prime_tensor).numpy()

Hasil penjumlahan :


array([[ 1.1440105,  3.9366663,  5.55711  ,  7.0746303,  9.398217 ],
       [13.883208 , 15.360186 , 21.116978 , 23.486507 , 29.881186 ],
       [32.179207 , 37.31829  , 40.694767 , 42.425564 , 48.641346 ],
       [53.185696 , 57.55285  , 61.323097 , 66.81747  , 69.7067   ],
       [71.8861   , 77.90552  , 83.01676  , 89.42492  , 97.93901  ]],
      dtype=float32)

In [115]:
#pengurangan
print(f'Hasil pengurangan :')
tf.subtract(random_tensor, prime_tensor).numpy()

Hasil pengurangan :


array([[ -2.8559895,  -2.0633337,  -4.44289  ,  -6.9253697, -12.601783 ],
       [-12.116792 , -18.639814 , -16.883022 , -22.513493 , -28.118814 ],
       [-29.820795 , -36.68171  , -41.305233 , -43.574436 , -45.358654 ],
       [-52.814304 , -60.44715  , -60.676903 , -67.18253  , -72.2933   ],
       [-74.1139   , -80.09448  , -82.98324  , -88.57508  , -96.06099  ]],
      dtype=float32)

In [117]:
#perkalian
print(f'Hasil perkalian :')
tf.multiply(random_tensor, prime_tensor).numpy()

Hasil perkalian :


array([[ -1.711979 ,   2.8099988,   2.7855482,   0.5224129, -17.619606 ],
       [ 11.48171  , -27.876844 ,  40.222572 ,  11.189658 ,  25.554373 ],
       [ 36.555367 ,  11.776733 , -12.514548 , -24.700687 ,  77.143265 ],
       [  9.841922 , -85.38197  ,  19.708939 , -12.229658 , -91.824135 ],
       [-81.31484  , -86.46383  ,   1.3912559,  37.817795 ,  91.08384  ]],
      dtype=float32)

In [118]:
#pembagian
print(f'Hasil pembagian : ')
tf.divide(random_tensor, prime_tensor).numpy()

Hasil pembagian : 


array([[-4.27994758e-01,  3.12222093e-01,  1.11421928e-01,
         1.06614884e-02, -1.45616591e-01],
       [ 6.79391176e-02, -9.64596719e-02,  1.11419864e-01,
         2.11524721e-02,  3.03856991e-02],
       [ 3.80388834e-02,  8.60243477e-03, -7.44470442e-03,
        -1.33589441e-02,  3.49222571e-02],
       [ 3.50371003e-03, -2.45280024e-02,  5.29667782e-03,
        -2.72436137e-03, -1.82154607e-02],
       [-1.52589316e-02, -1.38541628e-02,  2.01953240e-04,
         4.77437116e-03,  9.68050119e-03]], dtype=float32)

In [119]:
#pangkat
print(f'Hasil pangkat : ')
tf.pow(random_tensor, prime_tensor).numpy()

Hasil pangkat : 


array([[ 7.3271805e-01,  8.2177818e-01,  5.3666517e-02,  1.2894695e-08,
        -1.7808971e+02],
       [ 1.9898586e-01, -4.4823911e+03,  1.5438618e+06,  6.3539922e-08,
         2.5524072e-02],
       [ 1.6568127e+02,  4.0221202e-19, -7.4111233e-22, -4.4396088e-11,
         1.3013912e+10],
       [ 0.0000000e+00, -2.9535017e+09,  1.1731054e-30, -0.0000000e+00,
        -8.5230032e+07],
       [-2.6292327e+03, -1.2513604e+03,  0.0000000e+00,  8.3033045e-34,
         2.2333185e-03]], dtype=float32)

#### Tampilkan nilai maksimal dan minimal dari variable random_tensor

untuk menampilkan nilai maksimum atau minimum digunakan argmax() dan argmin()
<li> tf.argmax() : untuk mengalkulasi posisi nilai maksimum
<li> tf.argmin() : untuk mengalkulasi posisi nilai minimum

In [90]:
#tampilkan variabel random_tensor
random_tensor.numpy()

array([[-0.8559895 ,  0.93666625,  0.55710965,  0.07463042, -1.6017824 ],
       [ 0.8832085 , -1.6398144 ,  2.1169775 ,  0.48650688,  0.8811853 ],
       [ 1.1792054 ,  0.31829008, -0.30523288, -0.5744346 ,  1.6413461 ],
       [ 0.18569663, -1.4471521 ,  0.32309735, -0.1825322 , -1.2932976 ],
       [-1.113902  , -1.0944788 ,  0.01676212,  0.42491904,  0.93900865]],
      dtype=float32)

In [108]:
#nilai maksimal random_tensor dengan argmax()
tf.argmax(random_tensor, axis=1).numpy() #axis=1 untuk baris

array([1, 2, 4, 2, 4], dtype=int64)

In [109]:
#nilai minimum ranom_tensor dengan argmin()
tf.argmin(random_tensor, axis=0).numpy() #axis=0 untuk kolom

array([4, 1, 2, 2, 0], dtype=int64)

#### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [122]:
#menggabungkan 2 variabel dengan tf.concat()
tensor_gabung = tf.concat([random_tensor, prime_tensor], axis=0)
tensor_gabung.numpy()

array([[-8.5598952e-01,  9.3666625e-01,  5.5710965e-01,  7.4630417e-02,
        -1.6017824e+00],
       [ 8.8320851e-01, -1.6398144e+00,  2.1169775e+00,  4.8650688e-01,
         8.8118529e-01],
       [ 1.1792054e+00,  3.1829008e-01, -3.0523288e-01, -5.7443458e-01,
         1.6413461e+00],
       [ 1.8569663e-01, -1.4471521e+00,  3.2309735e-01, -1.8253221e-01,
        -1.2932976e+00],
       [-1.1139020e+00, -1.0944788e+00,  1.6762119e-02,  4.2491904e-01,
         9.3900865e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01]], dtype=float32)

#### Tampilkan hasil sorting dari kedua variable di atas (descending)

In [105]:
#mengurutkan variabel random_tensor secara descending
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[ 0.93666625,  0.55710965,  0.07463042, -0.8559895 , -1.6017824 ],
       [ 2.1169775 ,  0.8832085 ,  0.8811853 ,  0.48650688, -1.6398144 ],
       [ 1.6413461 ,  1.1792054 ,  0.31829008, -0.30523288, -0.5744346 ],
       [ 0.32309735,  0.18569663, -0.1825322 , -1.2932976 , -1.4471521 ],
       [ 0.93900865,  0.42491904,  0.01676212, -1.0944788 , -1.113902  ]],
      dtype=float32)

In [107]:
#mengurutkan variabel prime_tensor secara descending
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)